import Link from "next/link";
import { ArrowRight, Linkedin, Mail } from "lucide-react";
import { Logo } from "./Header";

const columns = [
  {title:"Produits",links:[["Recharge en déplacement","/#recharge-deplacement"],["Recharge en entreprise","/#recharge-entreprise"],["Recharge à domicile des collaborateurs","/#recharge-domicile"],["Supervision et pilotage","/solutions-techniques"],["Refacturation des recharges","/solutions-techniques"],["Solutions pour vos clients","/solutions/concessionnaires"]]},
  {title:"Partenariats",links:[["Réseaux de recharge","/contact"],["Installateurs de bornes","/contact"],["Concessionnaires & leasers","/solutions/concessionnaires"],["Devenir partenaire","/contact"]]},
  {title:"Ressources",links:[["Newsletter","/#newsletter"],["Blog","/ressources"],["Livres blancs","/resources/livre-blanc-monsieur-victor.pdf"],["Études de cas","/references"],["Guides pratiques","/ressources"],["FAQ","/#faq"],["Centre d’aide","/contact"]]},
  {title:"Entreprise",links:[["À propos","/a-propos"],["Notre méthode","/methode"],["Couverture géographique","/a-propos"],["Contact","/contact"],["Demander un devis","/devis"]]},
];

export function Footer(){return <footer className="bg-navy-950 text-slate-300"><section id="newsletter" className="border-b border-white/10"><div className="container grid gap-8 py-12 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-sm font-extrabold uppercase tracking-[.16em] text-electric-400">L’expertise Monsieur Victor au service de votre mobilité</p><h2 className="mt-3 text-2xl font-black text-white md:text-3xl">Recevez nos guides, décryptages et retours terrain.</h2></div><form action="/contact" method="get" className="flex w-full max-w-xl flex-col gap-3 sm:flex-row"><label htmlFor="newsletter-email" className="sr-only">Votre e-mail professionnel</label><div className="relative flex-1"><Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input id="newsletter-email" name="email" type="email" required placeholder="Votre e-mail professionnel" className="h-13 w-full rounded-xl border border-white/15 bg-white/10 pl-11 pr-4 text-white placeholder:text-slate-400"/></div><button className="btn-primary" type="submit">S’inscrire <ArrowRight size={17}/></button></form></div></section><div className="container py-16"><div className="mb-12 grid gap-10 border-b border-white/10 pb-12 lg:grid-cols-[1.15fr_4fr]"><div><Logo/><p className="mt-5 max-w-xs text-sm leading-6">Infrastructures de recharge pour entreprises en Belgique, en Wallonie et dans le nord de la France.</p><a href="mailto:projets@monsieur-victor.fr" className="mt-5 inline-block text-sm font-bold text-white">projets@monsieur-victor.fr</a></div><div className="grid gap-9 sm:grid-cols-2 xl:grid-cols-4">{columns.map(column=><div key={column.title}><h3 className="font-bold text-white">{column.title}</h3><div className="mt-5 grid gap-3 text-sm">{column.links.map(([label,href])=><Link key={label} href={href} className="transition hover:text-electric-400">{label}</Link>)}</div></div>)}</div></div><div className="flex flex-col justify-between gap-5 text-xs md:flex-row md:items-center"><p>© {new Date().getFullYear()} Monsieur Victor. Tous droits réservés.</p><div className="flex flex-wrap items-center gap-5"><Link href="/mentions-legales">Mentions légales</Link><Link href="/politique-de-confidentialite">Confidentialité</Link><Link href="/cgv">CGV</Link><a href="#" aria-label="LinkedIn Monsieur Victor"><Linkedin size={18}/></a></div></div></div></footer>}
