"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, ArrowRight, Building2, CarFront, CheckCircle2, Factory, ShoppingCart } from "lucide-react";
import { useSearchParams } from "next/navigation";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";

const schema = z.object({
  sector: z.string().min(1, "Sélectionnez votre secteur"),
  volume: z.string().min(1, "Indiquez un volume"), sites: z.coerce.number().min(1, "Minimum 1 site"),
  locations: z.string().min(2, "Indiquez une zone"), horizon: z.string().min(1, "Indiquez un horizon"),
  name: z.string().min(2, "Nom requis"), role: z.string().min(2, "Fonction requise"), company: z.string().min(2, "Entreprise requise"),
  email: z.string().email("Email professionnel invalide").refine(v=>!/(gmail|yahoo|hotmail|outlook)\./i.test(v), "Utilisez votre email professionnel"),
  phone: z.string().min(8, "Téléphone requis"), message: z.string().optional(), consent: z.literal(true,{errorMap:()=>({message:"Votre accord est requis"})}),
});
type FormData=z.infer<typeof schema>;
const sectorOptions=[{value:"loueurs-flottes",label:"Loueurs & flottes",icon:CarFront},{value:"concessionnaires",label:"Concessionnaires",icon:Building2},{value:"grande-distribution-stations-service",label:"Distribution & stations",icon:ShoppingCart},{value:"industriels-employeurs",label:"Industriels & employeurs",icon:Factory}];

export function MultiStepQuoteForm(){
  const search=useSearchParams(); const preset=search.get("secteur")||""; const [step,setStep]=useState(1); const [sent,setSent]=useState(false); const [serverError,setServerError]=useState("");
  const form=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{sector:preset,sites:1,consent:false as true}}); const {register,watch,setValue,trigger,handleSubmit,formState:{errors,isSubmitting}}=form;
  const fields=useMemo(()=>(step===1?["sector"]:step===2?["volume","sites","locations","horizon"]:step===3?["name","role","company","email","phone"]:[]) as (keyof FormData)[],[step]);
  async function next(){if(await trigger(fields))setStep(s=>Math.min(4,s+1));}
  async function submit(data:FormData){setServerError("");const res=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!res.ok){const json=await res.json().catch(()=>({}));setServerError(json.error||"Une erreur est survenue. Appelez-nous au 01 84 80 20 26.");return;}setSent(true)}
  if(sent)return <div className="card mx-auto max-w-2xl py-16 text-center"><CheckCircle2 className="mx-auto text-electric-600" size={56}/><h2 className="mt-6 text-3xl font-black text-navy-950">Votre demande est bien transmise.</h2><p className="mt-4 text-lg text-slate-600">Un expert Monsieur Victor vous recontacte sous 24h ouvrées pour qualifier le projet et convenir de la prochaine étape.</p></div>;
  const input="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3.5 outline-none transition focus:border-electric-500 focus:ring-4 focus:ring-electric-500/10";
  return <form onSubmit={handleSubmit(submit)} className="mx-auto max-w-4xl rounded-3xl border border-slate-200 bg-white p-5 shadow-soft md:p-10" noValidate>
    <div className="mb-10"><div className="flex justify-between text-xs font-bold uppercase tracking-wider text-slate-500"><span>Étape {step} sur 4</span><span>{step*25}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-electric-500 transition-all" style={{width:`${step*25}%`}}/></div></div>
    {step===1&&<section><h2 className="text-3xl font-black text-navy-950">Quel est votre secteur ?</h2><p className="mt-2 text-slate-600">Nous adaptons l’étude à votre modèle d’exploitation.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{sectorOptions.map(({value,label,icon:Icon})=><button type="button" key={value} onClick={()=>setValue("sector",value,{shouldValidate:true})} className={`flex items-center gap-4 rounded-2xl border p-5 text-left font-bold transition ${watch("sector")===value?'border-electric-500 bg-electric-500/5 ring-2 ring-electric-500/20':'border-slate-200 hover:border-slate-400'}`}><Icon className="text-electric-600"/><span>{label}</span></button>)}</div>{errors.sector&&<p className="error">{errors.sector.message}</p>}</section>}
    {step===2&&<section><h2 className="text-3xl font-black text-navy-950">Dimensionnons votre projet</h2><div className="mt-8 grid gap-6 md:grid-cols-2"><label className="label">Nombre de bornes<select {...register("volume")} className={input}><option value="">Choisir une tranche</option><option>1–10</option><option>10–50</option><option>50–100</option><option>100+</option></select><span className="error">{errors.volume?.message}</span></label><label className="label">Nombre de sites<input type="number" {...register("sites")} className={input}/><span className="error">{errors.sites?.message}</span></label><label className="label">Localisation(s)<input placeholder="Ex. Wallonie, Bruxelles, Lille et Hauts-de-France" {...register("locations")} className={input}/><span className="error">{errors.locations?.message}</span></label><label className="label">Horizon du projet<select {...register("horizon")} className={input}><option value="">Choisir</option><option>Immédiat / appel d’offres en cours</option><option>Sous 3 mois</option><option>Sous 6 mois</option><option>6 mois et plus</option></select><span className="error">{errors.horizon?.message}</span></label></div></section>}
    {step===3&&<section><h2 className="text-3xl font-black text-navy-950">Vos coordonnées professionnelles</h2><div className="mt-8 grid gap-6 md:grid-cols-2"><label className="label">Nom et prénom<input {...register("name")} className={input}/><span className="error">{errors.name?.message}</span></label><label className="label">Fonction<input {...register("role")} className={input}/><span className="error">{errors.role?.message}</span></label><label className="label">Entreprise<input {...register("company")} className={input}/><span className="error">{errors.company?.message}</span></label><label className="label">Email professionnel<input type="email" {...register("email")} className={input}/><span className="error">{errors.email?.message}</span></label><label className="label">Téléphone<input type="tel" {...register("phone")} className={input}/><span className="error">{errors.phone?.message}</span></label><label className="label md:col-span-2">Précisions utiles<textarea rows={4} {...register("message")} className={input}/></label></div></section>}
    {step===4&&<section><h2 className="text-3xl font-black text-navy-950">Vérifiez votre demande</h2><div className="mt-7 grid gap-3 rounded-2xl bg-slate-50 p-6 text-sm sm:grid-cols-2">{[["Secteur",watch("sector")],["Volume",watch("volume")],["Sites",watch("sites")],["Zone",watch("locations")],["Horizon",watch("horizon")],["Entreprise",watch("company")],["Contact",watch("name")],["Email",watch("email")]].map(([k,v])=><p key={String(k)}><span className="font-bold text-navy-950">{k} :</span> {String(v||"—")}</p>)}</div><label className="mt-6 flex items-start gap-3 text-sm text-slate-600"><input type="checkbox" {...register("consent")} className="mt-1 accent-emerald-500"/>J’accepte que Monsieur Victor utilise ces informations pour répondre à ma demande. Mes données ne seront pas revendues.</label><span className="error">{errors.consent?.message}</span>{serverError&&<p className="error mt-4">{serverError}</p>}</section>}
    <div className="mt-10 flex justify-between">{step>1?<button type="button" onClick={()=>setStep(s=>s-1)} className="btn-secondary"><ArrowLeft size={17}/> Retour</button>:<span/>}{step<4?<button type="button" onClick={next} className="btn-dark">Continuer <ArrowRight size={17}/></button>:<button disabled={isSubmitting} type="submit" className="btn-primary disabled:opacity-60">{isSubmitting?"Envoi…":"Envoyer ma demande"}<ArrowRight size={17}/></button>}</div>
  </form>
}
