import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export function Eyebrow({children}:{children:React.ReactNode}){return <p className="mb-4 text-sm font-extrabold uppercase tracking-[.16em] text-electric-600">{children}</p>}
export function HeroSection({eyebrow,title,description,secondary,imageLabel="Infrastructure de recharge pilotée"}:{eyebrow:string,title:string,description:string,secondary?:{label:string,href:string},imageLabel?:string}){return <section className="overflow-hidden bg-navy-950 text-white"><div className="container grid min-h-[620px] items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr]"><div><Eyebrow>{eyebrow}</Eyebrow><h1 className="max-w-4xl text-4xl font-black leading-[1.08] tracking-tight md:text-6xl">{title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">{description}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/devis" className="btn-primary">Demander un devis <ArrowRight size={18}/></Link>{secondary&&<Link href={secondary.href} className="btn-secondary-dark">{secondary.label}</Link>}</div><p className="mt-5 text-sm text-slate-400">Réponse par un expert sous 24h ouvrées · Étude initiale sans engagement</p></div><div className="relative min-h-[420px] rounded-4xl border border-white/10 bg-[radial-gradient(circle_at_70%_20%,rgba(0,214,127,.32),transparent_30%),linear-gradient(145deg,#12304b,#07131f)] p-8 shadow-2xl"><div className="absolute inset-8 rounded-3xl border border-white/10"></div><div className="relative flex h-full min-h-[356px] flex-col justify-between"><span className="w-fit rounded-full bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-wider">Pilotage multi-sites</span><div><div className="mb-5 flex items-end gap-3"><span className="text-6xl font-black text-electric-400">99,3%</span><span className="pb-2 text-sm text-slate-300">disponibilité<br/>réseau</span></div><p className="max-w-xs text-lg font-bold">{imageLabel}</p></div></div></div></div></section>}
export function SectionTitle({eyebrow,title,description}:{eyebrow:string,title:string,description?:string}){return <div className="max-w-3xl"><Eyebrow>{eyebrow}</Eyebrow><h2 className="text-3xl font-black tracking-tight text-navy-950 md:text-5xl">{title}</h2>{description&&<p className="mt-5 text-lg leading-8 text-slate-600">{description}</p>}</div>}
export function FeatureCard({icon:Icon,title,children}:{icon:LucideIcon,title:string,children:React.ReactNode}){return <div className="card"><span className="grid h-12 w-12 place-items-center rounded-xl bg-electric-500/10 text-electric-600"><Icon/></span><h3 className="mt-6 text-xl font-extrabold text-navy-950">{title}</h3><p className="mt-3 leading-7 text-slate-600">{children}</p></div>}
export function CheckList({items}:{items:readonly string[]}){return <ul className="grid gap-4">{items.map(i=><li key={i} className="flex gap-3 text-slate-700"><span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-electric-500/15 text-electric-600"><Check size={15}/></span>{i}</li>)}</ul>}
export function CTABanner({title="Votre programme de recharge mérite un plan fiable.",text="Parlez-nous de vos sites, de vos volumes et de votre calendrier. Nous vous répondons sous 24h ouvrées."}:{title?:string,text?:string}){return <section className="bg-electric-500"><div className="container flex flex-col items-start justify-between gap-7 py-12 md:flex-row md:items-center"><div><h2 className="text-3xl font-black text-navy-950">{title}</h2><p className="mt-2 max-w-2xl text-navy-950/75">{text}</p></div><Link href="/devis" className="btn-dark shrink-0">Demander une étude <ArrowRight size={18}/></Link></div></section>}
