import Link from "next/link";
import type { Metadata } from "next";
import { ArrowRight, BarChart3, Building2, Cable, CheckCircle2, Construction, Download, Gauge, HardHat, Home as HomeIcon, MapPin, ShieldCheck, Wrench, Zap } from "lucide-react";
import { caseStudies, faqs, sectors } from "@/lib/content";
import { CTABanner, SectionTitle } from "@/components/UI";
import { FAQAccordion } from "@/components/FAQAccordion";
import { BrandSelection } from "@/components/BrandSelection";

export const metadata:Metadata={title:"Installation de bornes électriques Belgique | Hauts-de-France",description:"Installation de bornes électriques pour entreprises en Belgique, en Wallonie et dans les Hauts-de-France : étude, travaux électriques, câblage, pose et mise en service."};

export default function Home(){return <>
  <section className="overflow-hidden bg-navy-950 text-white"><div className="container grid min-h-[680px] items-center gap-14 py-20 lg:grid-cols-[1.05fr_.95fr]"><div><p className="mb-4 text-sm font-extrabold uppercase tracking-[.16em] text-electric-400">Belgique · Wallonie · Hauts-de-France</p><h1 className="max-w-4xl text-4xl font-black leading-[1.06] tracking-tight md:text-6xl">Installation de bornes électriques pour entreprises.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Monsieur Victor réalise votre installation de bornes électriques en Belgique et dans les Hauts-de-France : étude, génie civil, câblage, protections, pose, raccordement et mise en service.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/devis" className="btn-primary">Faire étudier mon site <ArrowRight size={18}/></Link><Link href="/methode" className="btn-secondary-dark">Voir notre méthode de travaux</Link></div><div className="mt-8 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-300">{["Entreprises & flottes","Travaux clé en main","Déploiements multi-sites"].map(item=><span className="flex items-center gap-2" key={item}><CheckCircle2 size={17} className="text-electric-400"/>{item}</span>)}</div></div><div className="relative rounded-4xl border border-white/10 bg-[radial-gradient(circle_at_78%_18%,rgba(0,214,127,.28),transparent_28%),linear-gradient(145deg,#12304b,#07131f)] p-7 shadow-2xl"><div className="rounded-3xl border border-white/10 bg-white/5 p-7"><div className="flex items-center justify-between"><span className="rounded-full bg-electric-500/15 px-4 py-2 text-xs font-bold uppercase tracking-wider text-electric-400">Chantier clé en main</span><HardHat className="text-electric-400"/></div><div className="mt-12 grid gap-4 sm:grid-cols-2">{[[Cable,"Câblage & protections"],[Construction,"Percements & génie civil"],[Zap,"Raccordement électrique"],[ShieldCheck,"Contrôle & mise en service"]].map(([Icon,label])=>{const I=Icon as typeof Cable;return <div className="rounded-2xl border border-white/10 bg-navy-950/55 p-5" key={String(label)}><I className="text-electric-400"/><p className="mt-4 font-extrabold">{String(label)}</p></div>})}</div><p className="mt-7 text-sm leading-6 text-slate-300">Un responsable de projet coordonne les électriciens, le matériel, le planning et la remise du dossier technique.</p></div></div></div></section>

  <section className="border-b border-slate-200 bg-white"><div className="container grid gap-6 py-8 md:grid-cols-4">{[[MapPin,"Intervention transfrontalière","Belgique, Wallonie et Hauts-de-France"],[HardHat,"Travaux réalisés","Électricité, câblage et génie civil"],[Building2,"Déploiement multi-sites","Un standard technique, un planning consolidé"],[Wrench,"Après la pose","Maintenance et supervision"]].map(([Icon,title,text])=>{const I=Icon as typeof MapPin;return <div className="flex gap-4" key={String(title)}><I className="shrink-0 text-electric-600"/><div><p className="font-extrabold text-navy-950">{String(title)}</p><p className="mt-1 text-sm leading-6 text-slate-500">{String(text)}</p></div></div>})}</div></section>

  <section className="py-24"><div className="container"><SectionTitle eyebrow="Notre cœur de métier" title="Nous installons vos bornes, du tableau électrique jusqu’à la place de parking" description="Nous ne nous limitons pas à fournir une borne. Nous réalisons l’infrastructure électrique et les travaux nécessaires pour qu’elle fonctionne durablement, en sécurité et sans perturber votre activité."/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{[[BarChart3,"Étude électrique","Relevé du site, puissance disponible, usages, schémas et dimensionnement."],[Construction,"Préparation du chantier","Cheminements, tranchées, percements, massifs et protections mécaniques."],[Cable,"Tirage des câbles","Alimentations et communications posées selon le plan d’exécution."],[Zap,"Protections & raccordement","Tableaux, départs, protections et connexion des équipements."],[Wrench,"Pose des bornes","Fixation murale ou sur pied, paramétrage et signalétique."],[ShieldCheck,"Contrôle & réception","Essais, mise en service, dossier technique et prise en main."]].map(([Icon,title,text])=>{const I=Icon as typeof Cable;return <div className="rounded-3xl border border-slate-200 p-7" key={String(title)}><span className="grid h-12 w-12 place-items-center rounded-xl bg-electric-500/10 text-electric-600"><I/></span><h3 className="mt-6 text-xl font-extrabold text-navy-950">{String(title)}</h3><p className="mt-3 leading-7 text-slate-600">{String(text)}</p></div>})}</div><div className="mt-10 flex flex-wrap gap-3"><Link href="/methode" className="btn-dark">Découvrir notre méthode <ArrowRight size={17}/></Link><Link href="/solutions-techniques" className="btn-secondary">Voir les équipements proposés</Link></div></div></section>

  <BrandSelection/>

  <section className="py-24"><div className="container"><SectionTitle eyebrow="Deux lieux de recharge" title="Une installation adaptée à chaque usage" description="L’infrastructure reste le socle. Nous adaptons ensuite la borne, la puissance, les accès et les services à l’endroit où vos véhicules se rechargent."/><div className="mt-12 grid gap-6 lg:grid-cols-2"><article id="recharge-entreprise" className="card scroll-mt-28"><Building2 className="text-electric-600" size={30}/><h3 className="mt-6 text-2xl font-black text-navy-950">Recharge en entreprise</h3><p className="mt-4 leading-7 text-slate-600">Parkings de collaborateurs, dépôts, agences, concessions, commerces et sites industriels. Installation AC ou DC, évolutive et pensée pour l’exploitation.</p><Link href="/solutions-techniques" className="mt-7 inline-flex items-center gap-2 font-bold text-navy-950">Découvrir <ArrowRight size={17}/></Link></article><article id="recharge-domicile" className="card scroll-mt-28"><HomeIcon className="text-electric-600" size={30}/><h3 className="mt-6 text-2xl font-black text-navy-950">Recharge à domicile</h3><p className="mt-4 leading-7 text-slate-600">Étude et installation chez les collaborateurs disposant d’un véhicule de société, avec un parcours coordonné pour les déploiements en volume.</p><Link href="/solutions/loueurs-flottes" className="mt-7 inline-flex items-center gap-2 font-bold text-navy-950">Pour les flottes <ArrowRight size={17}/></Link></article></div></div></section>

  <section className="bg-navy-950 py-24 text-white"><div className="container grid items-center gap-14 lg:grid-cols-2"><div><p className="mb-4 text-sm font-extrabold uppercase tracking-[.16em] text-electric-400">Après l’installation</p><h2 className="text-3xl font-black tracking-tight md:text-5xl">Pilotez les bornes avec un logiciel, si votre projet l’exige.</h2><p className="mt-6 text-lg leading-8 text-slate-300">La supervision est une option complémentaire aux travaux. Elle devient utile pour gérer les accès, partager la puissance, suivre les consommations, rembourser certaines recharges ou consolider plusieurs sites.</p><ul className="mt-8 grid gap-4">{["Répartition dynamique de la puissance","Suivi des consommations et de la disponibilité","Gestion des badges, utilisateurs et tarifs","Exports pour flotte, finance et RSE"].map(item=><li className="flex gap-3" key={item}><CheckCircle2 className="mt-0.5 shrink-0 text-electric-400"/>{item}</li>)}</ul><Link href="/solutions-techniques" className="btn-primary mt-9">Voir la supervision <ArrowRight size={17}/></Link></div><div className="rounded-4xl border border-white/10 bg-white/5 p-8"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-400">Puissance du site</p><p className="mt-2 text-4xl font-black">160 kVA</p></div><Gauge className="text-electric-400" size={42}/></div><div className="mt-10 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full w-[68%] rounded-full bg-electric-500"/></div><div className="mt-3 flex justify-between text-xs text-slate-400"><span>108 kVA utilisés</span><span>52 kVA disponibles</span></div><div className="mt-9 grid grid-cols-2 gap-4"><div className="rounded-2xl bg-navy-950/60 p-5"><p className="text-2xl font-black text-electric-400">24</p><p className="mt-1 text-sm text-slate-300">points connectés</p></div><div className="rounded-2xl bg-navy-950/60 p-5"><p className="text-2xl font-black text-electric-400">98,7 %</p><p className="mt-1 text-sm text-slate-300">disponibilité affichée</p></div></div><p className="mt-5 text-xs text-slate-500">Illustration d’un tableau de supervision.</p></div></div></section>

  <section id="secteurs" className="py-24"><div className="container"><SectionTitle eyebrow="Votre secteur" title="Les travaux adaptés à vos contraintes d’exploitation"/><div className="mt-12 grid gap-5 md:grid-cols-2">{sectors.map(s=>{const Icon=s.icon;return <Link key={s.slug} href={`/solutions/${s.slug}`} className="card group"><Icon className="text-electric-600"/><h3 className="mt-5 text-2xl font-black text-navy-950">{s.short}</h3><p className="mt-3 leading-7 text-slate-600">{s.description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-navy-950">Voir les besoins techniques <ArrowRight size={17} className="transition group-hover:translate-x-1"/></span></Link>})}</div></div></section>

  <section className="bg-slate-50 py-24"><div className="container"><SectionTitle eyebrow="Exemple de déploiement" title="80 points de charge, 12 sites, une exécution coordonnée" description="Un exemple de programme multi-sites : audit commun, plans d’exécution, approvisionnement, travaux par vagues et réception centralisée."/><div className="mt-10 grid overflow-hidden rounded-4xl bg-white shadow-soft lg:grid-cols-2"><div className="bg-[radial-gradient(circle_at_30%_30%,rgba(0,214,127,.35),transparent_28%),linear-gradient(145deg,#184567,#07131f)] p-10 text-white"><p className="text-sm font-bold uppercase tracking-wider text-electric-400">Cas représentatif</p><p className="mt-20 text-5xl font-black">12 sites</p><p className="mt-2 text-slate-300">coordonnés sous un même standard de travaux</p></div><div className="p-10 lg:p-14"><h3 className="text-3xl font-black text-navy-950">Le même niveau de finition sur chaque implantation</h3><p className="mt-5 leading-7 text-slate-600">Relevés techniques, schémas, cheminements, protections, pose et essais sont documentés dans un dossier de réception commun.</p><Link href={`/references/${caseStudies[0].slug}`} className="btn-dark mt-8">Voir l’étude de cas <ArrowRight size={17}/></Link></div></div></div></section>

  <section className="py-24"><div className="container grid items-center gap-12 rounded-4xl bg-electric-500/10 p-8 md:p-12 lg:grid-cols-[1fr_auto]"><div><p className="text-sm font-extrabold uppercase tracking-[.16em] text-electric-600">Livre blanc Monsieur Victor</p><h2 className="mt-4 text-3xl font-black text-navy-950 md:text-4xl">Préparez votre installation de bornes en entreprise.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Un guide de 16 pages sur les usages, l’étude électrique, les travaux, la conformité, le budget, le pilotage et l’appel d’offres.</p></div><a href="/resources/livre-blanc-monsieur-victor.pdf" className="btn-dark" download><Download size={18}/> Télécharger gratuitement</a></div></section>

  <section id="faq" className="bg-slate-50 py-24"><div className="container grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><SectionTitle eyebrow="Questions fréquentes" title="Avant de lancer les travaux"/><FAQAccordion items={faqs}/></div></section>
  <CTABanner title="Un site à électrifier ? Commençons par l’étude technique." text="Indiquez-nous le nombre de bornes, les sites concernés et votre calendrier. Un expert vous répond sous 24h ouvrées."/>
</>}
